---
- name: construct
  hosts: construct
  become: yes

  tasks:
  - name: Ensure jdk package is present
    apt:
     name: default-jdk
     state: present

  - name: Ensure maven package is present
    apt:
     name: maven
     state: present

  - name: Ensure git package is present
    apt:
     name: git
     state: present

  - name: Clone git
    git:
     repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
     dest: /tmp/1

  - name: Maven build
    shell: mvn package
    args:
     chdir: /tmp/1

  - name: get result of maven build
    fetch:
     src: /tmp/1/target/hello-1.0.war
     dest: /tmp/fetched/
     flat: yes

- name: prod
  hosts: prod
  become: yes

  tasks:
  - name: Ensure jdk package is present
    apt:
     name: default-jdk
     state: present

  - name: Ensure tomcat8 package is present
    apt:
     name: tomcat8
     state: present

  - name: Copy result of maven build into Tomkat8 working directory
    copy:
     src: /tmp/fetched/hello-1.0.war
     dest: /var/lib/tomcat8/webapps

  - name: Restart tomcat8
    service:
     name: tomcat8
     state: restarted

  - name: Ensure tomcat8 package is started
    service:
     name: tomcat8
     state: started